name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.13
      uses: actions/setup-go@v2
      with:
        go-version: ^1.13

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Get dependencies for simple-api-server-without-framework
      run: |
        git config --global url."https://${{ secrets.GO_MODULES_TOKEN }}:x-oauth-basic@github.com/a-thug".insteadOf "https://github.com/a-thug"
        export GOPRIVATE="github.com/a-thug"
        cd simple-api-server-without-framework && go get -v -t -d ./...
        if [ -f Gopkg.toml ]; then
            curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
            dep ensure
        fi

    - name: Build for simple-api-server-without-framework
      run: cd simple-api-server-without-framework && go build -v ./...

    - name: Test for simple-api-server-without-framework
      run: cd simple-api-server-without-framework && go test -v ./...
    
    - name: Get dependencies for simple-api-server-with-echo
      run: |
        cd simple-api-server-with-echo && go get -v -t -d ./...
        if [ -f Gopkg.toml ]; then
            curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
            dep ensure
        fi

    - name: Build for simple-api-server-with-echo
      run: cd simple-api-server-with-echo && go build -v ./...
